spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: test_user_db
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    ROOT: INFO

token:
  access-expiration-days: 90
  key: ba35a6ede916fe0f683884ed2009f06ea4e10d977cf686d71bdad4e773d0b360
